name: Deploy to Hostinger

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build the React App
        run: npm run build

      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@master
        with:
          host: 62.72.50.33
          username: u792480622
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd public_html
            rm -rf *
            cp -r build/* .